### PR TITLE
Rename the default config file name to `.launchable.d/config.yml`

### PR DESCRIPTION
**Pull request by ninjinkun**
As @Konboi and I discussed, the config file should be `.launchable/config.yml`. However, I found Launchable CLI uses `.launchable` as a test session store. They are conflicting. So, I named the config file as `.launchable-config.yml`.

### CODE REVIEW

**Comment by Songmu** [comment]
How about .launchable.d/config.yaml?
Although seen less often these days, it is an occasional pattern to add a .d suffix to a directory, as in emacs.d or init.d.

Currently, the contents of the .launchable file used by launchable/cli may also be placed under that directory.

In this case, I think there could be a plan to migrate to using a .lanchable directory in the future.

**Comment by takanabe** [comment]
I vote .launchable.d/config.yaml because I personally don't like adding too many dotconfigs at the repository root.

**Comment by ninjinkun** [comment]
`.launchable.d/config.yaml` is a good idea! If there are no objections, I'll go with this one.

**Review by Konboi — APPROVED** [review]
LGTM

Great Work!

**Pull request merged**
